name: Send OTP Bot
on:
  repository_dispatch:
    types: [send-otp]

jobs:
  send-sms:
    runs-on: ubuntu-latest
    steps:
      - name: Call Twilio API
        run: |
          curl -X POST https://verify.twilio.com/v2/Services/${{ secrets.TWILIO_VERIFY_SID }}/Verifications \
          --data-urlencode "To=${{ github.event.client_payload.to }}" \
          --data-urlencode "Channel=sms" \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}
