name: Twilio Verify OTP
on:
  workflow_dispatch:
    inputs:
      to:
        description: 'User Phone Number'
        required: true

jobs:
  send-otp:
    runs-on: ubuntu-latest
    steps:
      - name: Send Verification Code
        run: |
          curl -X POST https://verify.twilio.com/v2/Services/${{ secrets.TWILIO_VERIFY_SID }}/Verifications \
          --data-urlencode "To=${{ github.event.inputs.to }}" \
          --data-urlencode "Channel=sms" \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}
